name: Update PE Data

on:
  schedule:
    - cron: '0 7 * * 1-5'  # 每个交易日 UTC 07:00 = 北京时间 15:00
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # 使用具有写入权限的令牌
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install yfinance pandas requests beautifulsoup4  # 添加 yfinance 和 pandas
        
      - name: Fetch PE data and generate data.json
        run: python app.py
        
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update PE data [skip ci]"
            git push origin HEAD:main
          fi
